version: "3.8"

services:
  frontend:
    container_name: frontend-job-application-tracker
    build: .
    ports:
      - "5173:5173"
    environment:
      VITE_BASE_URL: "http://localhost:3000/api"
    volumes:
      - .:/app
      - /app/node_modules
